name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run'     
        required: true
        default: 'development'
      mode:
        description: 'Running mode'  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running dev env
        if: github.event.inputs.environment == 'development'
        run: echo "Running dev env with mode ${{ github.event.inputs.mode }}"
      - name: Running prod env
        if: github.event.inputs.environment == 'production'
        run: echo "Running prod env with mode ${{ github.event.inputs.mode }}"
